set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports resetn]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVCMOS33} [get_ports lcd_e]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD LVCMOS33} [get_ports lcd_rs]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD LVCMOS33} [get_ports lcd_rw]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD LVCMOS33} [get_ports lcd_data[0]]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD LVCMOS33} [get_ports lcd_data[1]]
set_property -dict {PACKAGE_PIN Y3 IOSTANDARD LVCMOS33} [get_ports lcd_data[2]]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD LVCMOS33} [get_ports lcd_data[3]]
set_property -dict {PACKAGE_PIN AA5 IOSTANDARD LVCMOS33} [get_ports lcd_data[4]]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD LVCMOS33} [get_ports lcd_data[5]]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports lcd_data[6]]
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD LVCMOS33} [get_ports lcd_data[7]]

set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {digit[7]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {digit[6]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {digit[5]}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {digit[4]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {digit[3]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {digit[2]}]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports {digit[1]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {digit[0]}]

set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {seg_data[7]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {seg_data[6]}]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33} [get_ports {seg_data[5]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {seg_data[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {seg_data[3]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {seg_data[2]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {seg_data[1]}]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports {seg_data[0]}]

create_clock -name clk -period 10.0 [get_ports clk]
